export interface Profile{
    id: number,
    name: string,
    surName: string,
    phoneNumber: string,
    readmine: string,
    image: string,
    dateStart: string,
    dateEnd: string,
    idCard: string,
    numberBank: string,
    brankCompany: string,
    country: string,
    email: string,
    dob: string,
    address: string,
    status: string,
    department: string,
    position: string,
}